version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    image: eureka-server
    ports:
      - 8761:8761
    healthcheck:
      test: "exit 0"

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888
    healthcheck:
      test: "exit 0"

  zuul-api:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    image: zuul-api
    hostname: localhost
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"

  mongo:
    image: mongo:latest
    ports:
      - 27018:27018
    expose:
      - 27018
    container_name: mongo
    network_mode: host
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"

  user-service:
    build: user/
    depends_on:
      - mongo
    restart: always
    network_mode: host
    container_name: userregistration
    image: user
    hostname: localhost
    ports:
      - 8192:8192
    healthcheck:
      test: "exit 0"

  neo4j:
    build: neo4j/
    depends_on:
      - mongo
    restart: always
    network_mode: host
    container_name: neo4j
    image: neo4j
    hostname: localhost
    ports:
      - 8191:8191
    healthcheck:
      test: "exit 0"

  manufacture:
    build: manufacture/
    depends_on:
      - mongo
      - user
    restart: always
    network_mode: host
    container_name: manufacture
    image: manufacture
    hostname: localhost
    ports:
      - 8189:8189
    healthcheck:
      test: "exit 0"

  supplier:
    build: supplier/
    depends_on:
      - mongo
      - user
    restart: always
    network_mode: host
    container_name: supplier
    image: supplier
    hostname: supplier
    ports:
      - 8188:8188
    healthcheck:
      test: "exit 0"
      
  designer-dashboard:
    build: designer/
    depends_on:
      - mongo
      - user
    restart: always
    network_mode: host
    container_name: designer
    image: designer
    hostname: designer
    ports:
      - 8187:8187
    healthcheck:
      test: "exit 0"
      
  consumer:
    build: consumer/
      depends_on:
        - mongo
        - user
      restart: always
      network_mode: host
      container_name: consumer
      image: consumer
      hostname: consumer
      ports:
        - 8190:8190
      healthcheck:
        test: "exit 0"

  login:
    build: login/
      depends_on:
        - mongo
        - user
      restart: always
      network_mode: host
      container_name: login
      image: login
      hostname: login
      ports:
        - 8190:8190
      healthcheck:
        test: "exit 0"

  
